name: Release Docker Image
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      # This is a manual workaround until the latest tagging is fixed:
      # https://github.com/timescale/timescaledb-docker/issues/205
      no_tag_latest:
        description: 'Do not tag the published images as latest'
        type: boolean
        required: false
        default: false
env:
  ORG: masami10 #timescaledev
  TS_VERSION: ${{ github.event.inputs.version || '2.9.1' }}
jobs:
  timescaledb-bitnami:

    name: PG${{ matrix.pg }}-bitnami-repmgr
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg: [12, 13, 14]

    steps:
      - uses: actions/checkout@v3

    - name: Login to github Registry
      run: echo ${{ secrets.${{ secrets.TOKEN }} }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push amd64 Docker image for TimescaleDB-repmgr bitnami
      run: make push ORG=$ORG PG_VER=pg${{ matrix.pg }} TS_VERSION=$TS_VERSION
      working-directory: bitnami-repmgr

      - name: Build and push amd64 Docker image for TimescaleDB bitnami
        run: |
          if [ "${{ github.event.inputs.no_tag_latest }}" == "true" ]
          then
              export BETA=1
          fi
          make push ORG=$ORG PG_VER=pg${{ matrix.pg }} TS_VERSION=$TS_VERSION BETA=$BETA
        working-directory: bitnami
