name: Release Docker Image
on:
  push:
    branches: [ main ]
  repository_dispatch:
  workflow_dispatch:

env:
  ORG: ghcr.io/ethermeta-org
  TS_VERSION: ${{ github.event.inputs.version || secrets.RELEASE_VERSION || '2.9.2' }}
jobs:
  timescaledb-bitnami:

    name: PG${{ matrix.pg }}-bitnami-repmgr
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg: [12, 13, 14]

    steps:
      - uses: actions/checkout@v3

    - name: Login to github Registry
      run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push amd64 Docker image for TimescaleDB-repmgr bitnami
      run: make push ORG=$ORG PG_VER=pg${{ matrix.pg }} TS_VERSION=$TS_VERSION BETA=1
      working-directory: bitnami-repmgr
